---
- name: Install unzip
  apt:
      name: unzip      
      state: present      
  tags: [consul]

- name: Remove old consul versions
  file:
    dest: "{{item}}"
    state: absent
  with_items:
      - /usr/local/bin/consul
      - /usr/local/bin/consul-template
  tags: [consul, consul-template]

- name: Download consul
  get_url:
    url: https://releases.hashicorp.com/consul/{{consul_version}}/consul_{{consul_version}}_linux_amd64.zip
    dest: /tmp/consul.zip
  tags: [consul]

- name: Upack and install consul
  command: "{{item}}"
  args:
    chdir: /usr/local/bin/
  with_items:
      - unzip /tmp/consul.zip
      - chmod +x /usr/local/bin/consul      
  tags: [consul]

- name: Download consul-template
  get_url:
    url: https://releases.hashicorp.com/consul-template/{{consul_template_version}}/consul-template_{{consul_template_version}}_linux_amd64.zip
    dest: /tmp/consul_template.zip
  tags: [consul, consul-template]

- name: Upack and install consul-template
  command: "{{item}}"
  args:
    chdir: /usr/local/bin/
  with_items:
      - unzip /tmp/consul_template.zip
      - chmod +x /usr/local/bin/consul-template      
  tags: [consul, consul-template]

- name: Directories are present
  file:
    dest: "{{ item }}"
    state: directory
  with_items: "{{directories}}"
  tags: [consul]

- name: Files are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{files}}"
  tags: [consul]

- name: Templates are present
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items: "{{templates}}"
  tags: [consul]

- name: Service is started
  service:
    name=consul
    state=started
    pattern=/usr/local/bin/consul
  tags: [consul]

- name: Node is in cluster
  shell: consul join {{ consul_master_ip }}
  when: consul_master_ip is defined
  tags: [consul]

- name: Configurations are present
  template:
    src: consul_check.json.j2
    dest: /etc/consul.d/consul_check.json
  register: result
  tags: [consul]

- name: Consul is restarted
  shell: killall -HUP consul
  when: result|changed
  tags: [consul]

- name: Registrator is running
  docker:
    name: registrator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    hostname: "{{ hostname }}"
    image: gliderlabs/registrator
    command: -ip {{ ip }} consul://{{ ip }}:8500
  tags: [consul]

- name: Registrator KV is running
  docker:
    name: registrator-kv
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    hostname: "{{ hostname }}"
    image: gliderlabs/registrator
    command: -ip {{ ip }} consulkv://{{ ip }}:8500/services
  tags: [consul]