---
- name: Add Oracle Java Repository
  sudo: yes
  apt_repository: 
    repo: 'ppa:webupd8team/java'
    state: present
  tags: [java]

- name: Accept Java 8 License
  sudo: yes
  debconf:
    name: 'oracle-java8-installer' 
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'
  tags: [java]

- name: Package is present
  sudo: yes
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
    install_recommends: yes
  with_items:
    - oracle-java8-installer
    - ca-certificates    
    - oracle-java8-set-default
  tags: [java]