- hosts: swarm-master
  remote_user: vagrant
  become: true
  vars:
    - container_image: test_service
    - container_name: test_service
    - http_address: /
  roles:
    - docker
    - consul
    - swarm
    - service