consul_version: 0.6.4
consul_template_version: 0.14.0

directories:
  - /etc/consul.d
  - /data/consul
  - /data/consul/logs
  - /data/consul/scripts
  - /data/consul/config

files: [
  { src: "ui", dest: "/data/consul", mode: "0744" },
  { src: "mem.sh", dest: "/data/consul/scripts/mem.sh", mode: "0755" },
  { src: "disk.sh", dest: "/data/consul/scripts/disk.sh", mode: "0755" },
  { src: "jq", dest: "/usr/local/bin/jq", mode: "0755" },
]

templates: [
  { src: "consul.conf.j2", dest: "/etc/init/consul.conf", mode: "0644" },
]